name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        path: repo

    - name: Checkout build branch
      uses: actions/checkout@v3.3.0
      with:
        ref: "gh-pages"
        path: build

    - name: Download Dart Sass
      uses: robinraju/release-downloader@v1.7
      with:
        repository: "sass/dart-sass"
        latest: true
        fileName: "dart-sass-*-linux-x64.tar.gz"

    - name: Install Dart Sass
      run: |2
        tar -xzf dart-sass-*-linux-x64.tar.gz
        rm -rf dart-sass-*.tar.gz
        echo dart-sass >> $GITHUB_PATH

    - name: Compile Sass
      run: "sass repo/sass:build"

    - name: Copy HTML
      run: "cp -rf repo/html/* build/"

    - name: Push
      run: |2
        cd repo
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        git commit -m "Build"
        git push
