name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.3.0
      with:
        path: repo

    - name: Checkout build branch
      uses: actions/checkout@v3.3.0
      with:
        ref: "gh-pages"
        path: build

    - name: Download Dart Sass
      uses: robinraju/release-downloader@v1.7
      with:
        repository: "sass/dart-sass"
        latest: true
        fileName: "dart-sass-*-linux-x64.tar.gz"

    - name: Install Dart Sass
      run: |2
        tar -xzf dart-sass-*.tar.gz
        rm -rf dart-sass-*.tar.gz

    - name: Prepare build directory
      run: |2
        shopt -s extglob
        rm -rf build/!(.git/)
        mkdir build/assets/
        mkdir build/css/
        mkdir build/src/
        echo -n zelda.sr > build/CNAME

    - name: Copy files
      run: |2
        cp -rf repo/sass/ build/src/
        cp -rf repo/html/* build/
        cp -rf repo/fonts/ build/assets/
        cp -rf repo/images/ build/assets/

    - name: Compile Sass
      run: |2
        cd build/
        ../dart-sass/sass src/sass/:css/

    - name: Push
      run: |2
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add -A
        if ! git diff-index --quiet HEAD; then
          git commit -am "Build"
          git push
        fi
      if: ${{ github.event_name == 'push' }}
